### PR TITLE
Mysteriously fix hot reloading

### PR DESCRIPTION
**Pull request by ptomato**
I'm not sure why hot reloading wasn't working or why this fixes it, but it
seems to work now. The only clue I got was from the Webpack Development
Guide (https://webpack.js.org/guides/development/):

"Warning: webpack-dev-server doesn't write any output files after
compiling. Instead, it keeps bundle files in memory and serves them as if
they were real files mounted at the server's root path. If your page
expects to find the bundle files on a different path, you can change this
with the devMiddleware.publicPath option in the dev server's
configuration."

So, I looked under the devMiddleware config options and tried writeToDisk,
and at that point the app started hot-reloading.

I'm not sure if this is the correct solution though, because it also
writes the hot-update code to the bundle that is published to the web.

### CODE REVIEW

**Comment by sarahghp** [comment]
Hm, when I pull this down, I still don't see it hot reloading. How are you testing that? (I wonder if I am looing at the wrong thing, but I also don't see the notification in my console.)

**Comment by sarahghp** [comment]
Also, I see you have `output.clean` set to `true` and that means on my version it is cleaning up incremental versions. I think this could be taken out of draft and merged with the updated README.

**Comment by ptomato** [comment]
Summarizing some discussion - I hope this won't break the website, if it does we can revert it.

**Review by sarahghp — APPROVED** [review]
YOLO

**Pull request merged**
